-- =====================================================================
-- 레퍼런스 도메인(example) 테이블  [PostgreSQL]
--
-- ddl-auto 가 validate 이므로, 매핑된 엔티티의 테이블이 없으면 애플리케이션이 시작에 실패한다.
-- ExampleJpaEntity 가 "examples" 테이블에 매핑되어 있어 이 테이블이 필요하다.
--
-- example 은 새 도메인을 만들 때 복사해서 쓰는 레퍼런스 도메인이다(README 참고).
-- 레퍼런스 도메인을 지우면 이 파일도 함께 지우고 테이블을 DROP 한다.
--
-- 실행 (psql):
--   psql -U pairing -d pairing -v ON_ERROR_STOP=1 -f db/init/99-create-example-table.sql
--
-- 컬럼 정의는 ExampleJpaEntity 의 매핑을 그대로 따른다.
-- 엔티티를 바꾸면 이 파일도 같이 바꿔야 한다.
-- =====================================================================

CREATE TABLE "examples" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "active" BOOLEAN NOT NULL,
    -- S3 object key(상대경로)만 저장한다. CDN 절대 URL 은 저장하지 않는다.
    "image_url" VARCHAR(512),
    PRIMARY KEY ("id")
);

COMMENT ON TABLE "examples" IS '레퍼런스 도메인 예시 테이블(운영 도메인 아님)';
